import 'package:cartzy_app/feature/cart/data/model/response/cart_item_model.dart';
import 'package:cartzy_app/feature/home/domain/entities/category_entity.dart';

abstract class AppAssets {
  static String dummyNetworkImage = 'https://i.imgur.com/QkIa5tT.jpeg';

  static String emptyProductListImage = 'assets/image/empty_product.png';

  static List<CategoryEntity> get dummyCategories => [
        CategoryEntity(
          id: 0,
          name: 'dymmy ',
          slug: 'dymmydymmydymmy  ',
          image: dummyNetworkImage,
        ),
        CategoryEntity(
          id: 0,
          name: 'dymmy ',
          slug: 'dymmydymmydymmy  ',
          image: dummyNetworkImage,
        ),
        CategoryEntity(
          id: 0,
          name: 'dymmy ',
          slug: 'dymmydymmydymmy  ',
          image: dummyNetworkImage,
        ),
        CategoryEntity(
          id: 0,
          name: 'dymmy ',
          slug: 'dymmydymmydymmy  ',
          image: dummyNetworkImage,
        ),
        CategoryEntity(
          id: 0,
          name: 'dymmy ',
          slug: 'dymmydymmydymmy  ',
          image: dummyNetworkImage,
        ),
      ];

  static List<CartItemModel> get dummyCartItems => [
        CartItemModel(
          isFavorite: true,
          productId: 2,
          title: 'Dummy Product 1',
          price: 99,
          quantity: 5,
          slug: 'dummy-product-1',
          description: 'This is a dummy product.',
          category: CategoryEntity(
            id: 0,
            name: 'dymmy ',
            slug: 'dymmydymmydymmy  ',
            image: dummyNetworkImage,
          ),
          images: [dummyNetworkImage],
        ),
        CartItemModel(
          isFavorite: false,
          productId: 3,
          title: 'Dummy Product 2',
          price: 49,
          quantity: 2,
          slug: 'dummy-product-2',
          description: 'This is another dummy product.',
          category: CategoryEntity(
            id: 0,
            name: 'dymmy ',
            slug: 'dymmydymmydymmy  ',
            image: dummyNetworkImage,
          ),
          images: [dummyNetworkImage],
        ),
        CartItemModel(
          isFavorite: true,
          productId: 4,
          title: 'Dummy Product 3',
          price: 79,
          quantity: 3,
          slug: 'dummy-product-3',
          description: 'This is yet another dummy product.',
          category: CategoryEntity(
            id: 0,
            name: 'dymmy ',
            slug: 'dymmydymmydymmy  ',
            image: dummyNetworkImage,
          ),
          images: [dummyNetworkImage],
        ),
        CartItemModel(
          isFavorite: false,
          productId: 5,
          title: 'Dummy Product 4',
          price: 59,
          quantity: 1,
          slug: 'dummy-product-4',
          description: 'This is the last dummy product.',
          category: CategoryEntity(
            id: 0,
            name: 'dymmy ',
            slug: 'dymmydymmydymmy  ',
            image: dummyNetworkImage,
          ),
          images: [dummyNetworkImage],
        ),
        CartItemModel(
          isFavorite: true,
          productId: 6,
          title: 'Dummy Product 5',
          price: 89,
          quantity: 4,
          slug: 'dummy-product-5',
          description: 'This is yet another dummy product.',
          category: CategoryEntity(
            id: 0,
            name: 'dymmy ',
            slug: 'dymmydymmydymmy  ',
            image: dummyNetworkImage,
          ),
          images: [dummyNetworkImage],
        ),
        CartItemModel(
          isFavorite: false,
          productId: 7,
          title: 'Dummy Product 6',
          price: 69,
          quantity: 2,
          slug: 'dummy-product-6',
          description: 'This is the last dummy product.',
          category: CategoryEntity(
            id: 0,
            name: 'dymmy ',
            slug: 'dymmydymmydymmy  ',
            image: dummyNetworkImage,
          ),
          images: [dummyNetworkImage],
        ),
        CartItemModel(
          isFavorite: true,
          productId: 2,
          title: 'Dummy Product 1',
          price: 99,
          quantity: 5,
          slug: 'dummy-product-1',
          description: 'This is a dummy product.',
          category: CategoryEntity(
            id: 0,
            name: 'dymmy ',
            slug: 'dymmydymmydymmy  ',
            image: dummyNetworkImage,
          ),
          images: [dummyNetworkImage],
        ),
        CartItemModel(
          isFavorite: false,
          productId: 3,
          title: 'Dummy Product 2',
          price: 49,
          quantity: 2,
          slug: 'dummy-product-2',
          description: 'This is another dummy product.',
          category: CategoryEntity(
            id: 0,
            name: 'dymmy ',
            slug: 'dymmydymmydymmy  ',
            image: dummyNetworkImage,
          ),
          images: [dummyNetworkImage],
        ),
        CartItemModel(
          isFavorite: true,
          productId: 4,
          title: 'Dummy Product 3',
          price: 79,
          quantity: 3,
          slug: 'dummy-product-3',
          description: 'This is yet another dummy product.',
          category: CategoryEntity(
            id: 0,
            name: 'dymmy ',
            slug: 'dymmydymmydymmy  ',
            image: dummyNetworkImage,
          ),
          images: [dummyNetworkImage],
        ),
        CartItemModel(
          isFavorite: false,
          productId: 5,
          title: 'Dummy Product 4',
          price: 59,
          quantity: 1,
          slug: 'dummy-product-4',
          description: 'This is the last dummy product.',
          category: CategoryEntity(
            id: 0,
            name: 'dymmy ',
            slug: 'dymmydymmydymmy  ',
            image: dummyNetworkImage,
          ),
          images: [dummyNetworkImage],
        ),
        CartItemModel(
          isFavorite: true,
          productId: 6,
          title: 'Dummy Product 5',
          price: 89,
          quantity: 4,
          slug: 'dummy-product-5',
          description: 'This is yet another dummy product.',
          category: CategoryEntity(
            id: 0,
            name: 'dymmy ',
            slug: 'dymmydymmydymmy  ',
            image: dummyNetworkImage,
          ),
          images: [dummyNetworkImage],
        ),
        CartItemModel(
          isFavorite: false,
          productId: 7,
          title: 'Dummy Product 6',
          price: 69,
          quantity: 2,
          slug: 'dummy-product-6',
          description: 'This is the last dummy product.',
          category: CategoryEntity(
            id: 0,
            name: 'dymmy ',
            slug: 'dymmydymmydymmy  ',
            image: dummyNetworkImage,
          ),
          images: [dummyNetworkImage],
        ),
      ];
}
